name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install --upgrade pip
        pip install buildozer cython
        sudo apt-get install -y openjdk-8-jdk

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools
        mkdir -p android-sdk
        yes | ./cmdline-tools/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
        ./cmdline-tools/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-30" "build-tools;35.0.0"

    - name: Build the app
      run: buildozer android debug
