name: Build with Buildozer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install buildozer cython

    - name: Install NDK
      run: |
        mkdir -p $ANDROID_HOME/ndk
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d $ANDROID_HOME/ndk
        mv $ANDROID_HOME/ndk/android-ndk-r25b $ANDROID_HOME/ndk/25.1.8937393

    - name: Build the APK
      run: buildozer android debug
